name: Build and publish

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ./sw-embed
        run: |
          npm install
          npm run build

      - name: Copy outputs into version folders
        run: |
          commit=`git rev-parse HEAD`
          foldername="build-${commit}"
          mkdir "sw-embed/dist/$foldername/"
          cp sw-embed/dist/sw-embed.* "sw-embed/dist/$foldername/"

      - uses: jakejarvis/s3-sync-action@master
        name: publish
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SOURCE_DIR: 'sw-embed/dist'
          DEST_DIR: 'lib/sw-embed'
